name: deploy-auth

on:
  push:
    branches: [ main ]  
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: auth  

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t abdelrahman370/auth .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push image
        run: docker push abdelrahman370/auth

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITAL_OCEAN_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl
